---
title: "Alpha diversity"
output: html_document
date: "2025-01-13"
---

__Load library__
```{r}
library(tidyverse)
library(dplyr)
library(reshape2)
library(circlize)
library(ggplot2)
library(ggpubr)
```

__Importing and cleaning data__
```{r}
div <- read.csv("../data/divAlfa.csv",sep=",",header = T)

div <- melt(div, id.vars = c("ID","EDAD","GENERO","DIABETES","OTRA.ENFERMEDAD",
                                     "FUMADORES","ETAPA.PERIODONTAL","CEPILLADO"),
                    variable.name = "DIV")
div$ETAPA.PERIODONTAL<-factor(div$ETAPA.PERIODONTAL,
                              levels = c("Leve","Moderada","Grave"))
head(div)
```



```{r}
levels(div$ETAPA.PERIODONTAL)

ALFA <- ggplot(div)+ 
  geom_col(aes(reorder(ID,value),value, fill= ETAPA.PERIODONTAL),col="black")+
  facet_grid(DIV~., scales = "free",
             labeller = labeller(DIV=c("Shannon"="Shannon",
                                       "Dominancia"="Dominance",
                                       "OTUs"="OTUs")))+
  scale_fill_manual(labels=c("Mild","Moderate","Severe"),
                    values = c("#FFF300","#FFA54F","#FF3030"))+
  theme_pubr()+
  labs(x="Sample",y="", fill="Periodontitis",title="Alpha Diversity")+
  theme(axis.text.x = element_blank())

ALFA
```


```{r}
ALFASEP<-ggplot(div)+ 
  geom_col(aes(reorder(ID,value),value, fill= ETAPA.PERIODONTAL),col="black")+
  facet_grid(DIV~DIABETES, scales = "free",
             labeller = labeller(DIABETES=c("Diabeticos"="Diabetics",
                                 "Controles"="Control"),
                                 DIV=c("Shannon"="Shannon",
                                       "Dominancia"="Dominance",
                                       "OTUs"="OTUs"),
                                 ETAPA.PERIODONTAL=c("Leve"="Mild",
                                                     "Moderada"="Moderate",
                                                     "Grave"="Severe")))+
  scale_fill_manual(labels=c("Mild","Moderate","Severe"),
                    values = c("#FFF300","#FFA54F","#FF3030"))+
  theme_pubr()+
  labs(x="Sample",y="", fill="Periodontitis",title="Alpha Diversity by group")+
  theme(axis.text.x = element_blank())
ALFASEP
```

